development:
  adapter: postgresql
  encoding: unicode
  database: taskapp_development
  pool: 5
  timeout: 5000
  username: maxim
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: taskapp_test
  pool: 5
  timeout: 5000
  username: maxim
  password:
